# Generated by Django 4.2 on 2024-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdata',
            name='farmer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
