# Generated by Django 4.2 on 2024-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
