# Generated by Django 4.2 on 2024-12-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_farmer_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='data',
            new_name='Crop_name',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='image',
            new_name='Image',
        ),
        migrations.AddField(
            model_name='farmer',
            name='Accuracy',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Azimuth',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Farmer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Farmer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Pitch',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
