# Generated by Django 4.2 on 2024-12-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_farmerdata_farmer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerdata',
            old_name='crop_name',
            new_name='cropname',
        ),
        migrations.RenameField(
            model_name='farmerdata',
            old_name='farmer_id',
            new_name='farmerid',
        ),
        migrations.RenameField(
            model_name='farmerdata',
            old_name='farmer_name',
            new_name='farmername',
        ),
    ]
