# Generated by Django 4.2 on 2024-12-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_rename_data_farmer_crop_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Accuracy',
            new_name='accuracy',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Azimuth',
            new_name='azimuth',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Crop_name',
            new_name='crop_name',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Farmer_id',
            new_name='farmer_id',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Farmer_name',
            new_name='farmer_name',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Pitch',
            new_name='pitch',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Time',
            new_name='time',
        ),
    ]
