# Generated by Django 4.2 on 2024-12-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmerdata_time_stamb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
