# Generated by Django 4.2 on 2024-12-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_rename_accuracy_farmer_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='accuracy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
