# Generated by Django 4.2 on 2024-12-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_alter_farmerdata_latitude_alter_farmerdata_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerdata',
            options={'ordering': ['-time_stamb']},
        ),
    ]
