# Generated by Django 4.2 on 2024-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_alter_farmer_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
