# Generated by Django 4.2 on 2024-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_alter_farmer_azimuth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='crop_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='pitch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
